name: Main		
on: push		
jobs:		
  test:		
    runs-on: ubuntu-latest		
    steps:		
      - uses: actions/checkout@v1		
      - name: Use Node.js 12		
        uses: actions/setup-node@v1		
        with:		
          node-version: 12		
      - name: hello		
        run: |		
          echo Hello		
      - name: hello-node		
        run: |		
          node -e "console.log('Hello Node')"
