name: Main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: hello
        run: |
          echo Hello
      - name: hello-world
        run: |
          echo Hello World
